# Generated by Django 4.0.3 on 2022-03-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightNumber', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('departureAirport', models.CharField(max_length=10)),
                ('arrivalAirport', models.CharField(max_length=10)),
                ('flightDate', models.IntegerField()),
                ('aircraft', models.CharField(max_length=10)),
                ('paxAvailable', models.IntegerField()),
                ('paxBooked', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
